# IBM-Project-52610-1661013317

## University Admit Eligibility Predictor

## Importing The Libraries

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Reading the dataset

In [ ]:
df=pd.read_csv("data.csv")

## Analyze The Data

In [ ]:
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,7
1,324,107,4,4.0,4.5,8.87,1,5
2,316,104,3,3.0,3.5,8.00,1,5
3,322,110,3,3.5,2.5,8.67,1,5
4,314,103,2,2.0,3.0,8.21,0,4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   GRE Score          400 non-null    int64
 1   TOEFL Score        400 non-null    int64
 2   University Rating  400 non-null    int64
 3   SOP                400 non-null    float64
 4   LOR                400 non-null    float64
 5   CGPA               400 non-null    float64
 6   Research           400 non-null    int64
 7   Chance of Admit    400 non-null    int64
dtypes: float64(3), int64(5)
memory usage: 25.1 KB

In [ ]:
df.describe()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,4.712500
std,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,1.452625
min,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,1.000000
25%,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,4.000000
50%,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,5.000000
75%,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,6.000000
max,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,7.000000

## Handling Missing Values

In [ ]:
df.isnull().any()

GRE Score            False
TOEFL Score          False
University Rating    False
SOP                  False
LOR                  False
CGPA                 False
Research             False
Chance of Admit      False
dtype: bool

## Data Visualization

In [ ]:
import seaborn as sns

In [ ]:
from matplotlib import pyplot as plt

## Splitting Dependent And Independent Columns

In [ ]:
x=df.iloc[:,0:7].values
x

array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
       [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
       [316.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [330.  , 116.  ,   4.  , ...,   4.5 ,   9.45,   1.  ],
       [312.  , 103.  ,   3.  , ...,   4.  ,   8.78,   0.  ],
       [333.  , 117.  ,   4.  , ...,   4.  ,   9.66,   1.  ]])

In [ ]:
y=df.iloc[:,7:].values
y

array([[7],
       [5],
       [5],
       [5],
       [4],
       [6],
       [5],
       [4],
       [2],
       [2],
       [3],
       [6],
       [5],
       [4],
       [4],
       [3],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [7],
       [7],
       [7],
       [7],
       [5],
       [2],
       [2],
       [3],
       [4],
       [5],
       [7],
       [6],
       [7],
       [6],
       [4],
       [3],
       [3],
       [2],
       [2],
       [2],
       [3],
       [6],
       [7],
       [6],
       [6],
       [6],
       [6],
       [5],
       [5],
       [3],
       [5],
       [5],
       [4],
       [4],
       [4],
       [2],
       [1],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3],
       [4],
       [3],
       [4],
       [5],
       [7],
       [7],
       [7],
       [6],
       [5],
       [5],
       [5],
       [4],
       [2],
       [2],
       [2],
       [7],
       [7],
       [7],
       [7],
       [5],
       [5],
       [4],
       [4],
       [5],
       [4],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [6],
       [6],
       [5],
       [5],
       [4],
       [4],
       [3],
       [5],
       [4],
       [6],
       [7],
       [7],
       [4],
       [4],
       [4],
       [4],
       [5],
       [3],
       [4],
       [3],
       [2],
       [2],
       [5],
       [7],
       [7],
       [3],
       [4],
       [3],
       [4],
       [6],
       [5],
       [6],
       [7],
       [7],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [5],
       [5],
       [5],
       [6],
       [6],
       [7],
       [7],
       [5],
       [6],
       [5],
       [6],
       [7],
       [5],
       [7],
       [7],
       [6],
       [5],
       [5],
       [5],
       [4],
       [4],
       [4],
       [3],
       [3],
       [3],
       [4],
       [4],
       [6],
       [5],
       [4],
       [4],
       [4],
       [4],
       [4],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [5],
       [4],
       [5],
       [5],
       [6],
       [6],
       [7],
       [7],
       [6],
       [6],
       [6],
       [6],
       [7],
       [5],
       [5],
       [5],
       [5],
       [4],
       [5],
       [5],
       [5],
       [7],
       [7],
       [4],
       [3],
       [4],
       [4],
       [4],
       [4],
       [5],
       [6],
       [7],
       [7],
       [7],
       [7],
       [7],
       [6],
       [6],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [4],
       [4],
       [4],
       [5],
       [6],
       [5],
       [5],
       [4],
       [4],
       [7],
       [6],
       [6],
       [6],
       [4],
       [3],
       [3],
       [4],
       [4],
       [5],
       [4],
       [6],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [5],
       [7],
       [6],
       [5],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [4],
       [4],
       [5],
       [5],
       [5],
       [5],
       [6],
       [5],
       [5],
       [3],
       [2],
       [3],
       [3],
       [5],
       [6],
       [4],
       [4],
       [4],
       [4],
       [5],
       [6],
       [5],
       [7],
       [7],
       [7],
       [6],
       [6],
       [5],
       [3],
       [3],
       [3],
       [4],
       [4],
       [4],
       [5],
       [6],
       [6],
       [5],
       [4],
       [4],
       [4],
       [5],
       [4],
       [5],
       [5],
       [5],
       [4],
       [4],
       [5],
       [6],
       [5],
       [4],
       [4],
       [4],
       [3],
       [3],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [4],
       [6],
       [4],
       [4],
       [5],
       [2],
       [5],
       [5],
       [5],
       [5],
       [5],
       [6],
       [5],
       [7],
       [6],
       [6],
       [5],
       [5],
       [3],
       [3],
       [2],
       [2],
       [2],
       [2],
       [3],
       [4],
       [5],
       [5],
       [4],
       [4],
       [3],
       [5],
       [5],
       [4],
       [4],
       [6],
       [6],
       [7],
       [7],
       [4],
       [5],
       [6],
       [5],
       [3],
       [3],
       [4],
       [5],
       [6],
       [7],
       [5],
       [1],
       [1],
       [1],
       [2],
       [3],
       [5],
       [5],
       [5],
       [6],
       [4],
       [7],
       [7],
       [2],
       [3],
       [2],
       [5],
       [4],
       [5],
       [6],
       [5],
       [6],
       [6],
       [6],
       [7],
       [4],
       [7]])

## Splitting The Data Into Train And Test

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
y_train=(y_train>0.5)

In [ ]:
y_train

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [ ]:
y_test=(y_test>0.5)

In [ ]:
y_test

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

## Model Building

## Training And Testing The Model

In [ ]:
%matplotlib inline

In [ ]:
import io
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats
import scipy.special
import seaborn as sns

In [ ]:
import sklearn.linear_model

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
cls = LogisticRegression(random_state=0)